### ISSUE TITLE
Possible to get game into impossible position when player needs to pass.

### ISSUE THREAD

**Issue by vaguerant** [MrJPGames/Othello-3DS#1]
It's probably easiest just to show an image of the game at the point where I got stuck:
![win_20151007_02_23_41_pro](https://cloud.githubusercontent.com/assets/5259025/10313388/0b83db2e-6c9b-11e5-9afd-de413d2eaf53.jpg)
Sorry about the horizontal view, I guess GitHub doesn't understand JPEG rotation data.

As you can see, I was playing against the CPU here and got into a spot where there are no valid placements for my pieces, but the game seems to think there are. Touching any of them does nothing, but the game hasn't locked up; I can hit New Game to start a new game and such.

I'm not a very good Reversi/Othello player so I'm not sure if I'll be able to get the issue to recur to ensure that it always happens. I feel like I've seen the CPU player pass before, but maybe there's nothing implemented for a human player to pass? Again, I'm not sure.

Thanks for your time.

**EDIT:** I just recreated a similar situation by playing in two player mode (it was harder than I expected to arrange things the way I wanted even that way, hehehe) and it seemed to work fine there. Once I reached the point where the white player had walled off a corner as in my screenshot above, the black player simply got two turns in a row, i.e. the white player passed.

I have no idea why the situation in my screenshot didn't cause a pass. Unless it was the AI black player's turn in my screenshot and they were stuck "thinking"? Except for that extra third dot where the black player couldn't have played; the other two options for black player were terrible, so maybe the AI wasn't able to find a "best" position? Just throwing out guesses here, I have no understanding of what goes on under the hood.

**Comment by MrJPGames** [comment]
Thank you so much for reporting this issue! The image displays correctly on my IOS app that I monitor github with, it is indeed strange that it doesn't work on the web version.

Your last theory would be most logical, you're obviously seeing the possibilities of the black player not the white one, meaning it probably didn't properly skip the player's turn. The CPU however is definitely not thinking, it is a rather simple AI meaning that while it's thinking nothing else happens (meaning if it was stuck thinking you couldn't start a new game and such).

I would love to fix this issue, but I will first have to find a reliable way to get to this bug in order to see if it's actually fixed. And neither am I a great (enough) player to achieve that very easily (if at all).

I will try to make a board that can easily recreate the board from the image (as I can change the board you start with of course.) This should make testing easier.

Again thanks for reporting this issue, I don't know if I'll be able to fix it but I'll try!

Edit: Good news I was able to recreate the bug!
![image](https://cloud.githubusercontent.com/assets/2345643/10317409/8ed55b24-6c64-11e5-93a0-2b4adee2ddb2.png)
Bad news I still don't really know what's causing it :(

**Comment by MrJPGames** [comment]
So yeah found the issue, it didn't properly handle a no possible move state. It would detect it but wouldn't actually change who's turn it was. It's fixed in the latest release.

Again thanks for reporting the issue!

**Comment by vaguerant** [comment]
Great work, thanks JP, playing the updated version now. Much appreciated!
